"""Seed Hermes's USER.md from the canonical project YAML.

This is the ONLY way to refresh USER.md. The bridge must never write it.
What this script writes:

- Research interests (verbatim from user_profile.yaml)
- Keywords (joined list)
- Top skill clusters with weights
- Static facts about the user (Canada/EU targets, intake year, etc.)

What this script does NOT write (intentional):

- Planning data (workspaces, goals, tasks, decisions) — Postgres-only
- Saved papers/jobs/professors — those have their own MCP tools
- Style preferences or recent trends — Hermes native memory owns those

Run after editing data/user_profile.yaml:

    uv run python -m scripts.seed_hermes_memory

The script prints a diff of the change so you can review what moved
before committing.
"""

from __future__ import annotations

import difflib
import sys
from pathlib import Path

import yaml


HERMES_USER_MD = Path.home() / ".hermes" / "memories" / "USER.md"
PROJECT_ROOT = Path(__file__).resolve().parent.parent
PROFILE_PATH = PROJECT_ROOT / "data" / "user_profile.yaml"
SKILLS_PATH = PROJECT_ROOT / "data" / "user_skills.yaml"


def _load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def build_user_md() -> str:
    """Build USER.md content from the project YAML. Pure function for testing."""
    profile = _load_yaml(PROFILE_PATH)
    skills_raw = _load_yaml(SKILLS_PATH).get("skills", {})

    interests = (profile.get("research_interests") or "").strip()
    keywords = ", ".join(profile.get("keywords") or [])

    # Top 6 clusters by weight — enough for context, not bloat
    clusters = sorted(
        skills_raw.items(),
        key=lambda kv: kv[1].get("weight", 0.0),
        reverse=True,
    )[:6]
    cluster_lines = [
        f"- {name} (weight {body.get('weight', 1.0)}): {', '.join(body.get('skills', [])[:4])}"
        for name, body in clusters
    ]

    prefs = profile.get("preferences", {}) or {}
    arxiv = ", ".join(profile.get("arxiv_categories", []) or [])

    return f"""# Career Copilot user model

> **Auto-generated by `scripts/seed_hermes_memory.py`. Do not edit by hand — re-run the script after editing the project YAML.**
> This file is the one durable channel that reaches Hermes (the API server composes its own prompt and ignores a `system` message). It carries ONLY the canonical profile, not planning data — planning lives in Postgres via `career.planning.*` MCP tools.

## Research interests
{interests[:1500]}

## Keywords
{keywords}

## Top skill clusters
{chr(10).join(cluster_lines)}

## Active arXiv categories
{arxiv}

## Preferences
- Digest time: {prefs.get("digest_time", "—")}
- Digest days: {", ".join(prefs.get("digest_days", []) or [])}
- Min similarity: {profile.get("filters", {}).get("min_similarity", "—")}

## Workflow facts
- The user is a BSc CS student targeting a Master's degree.
- Primary region: Canada. Secondary: EU. Future: Africa remote.
- They prefer research-oriented recommendations and implementable work.
- They will ask questions via Telegram. Career Copilot bot is the front door.
- Planning data (goals, tasks, decisions, schools) lives in Postgres, NOT here.
  Use the `career.planning.*` tools to read or write that data.
- Style: concise, Telegram-friendly replies.
"""


def main() -> int:
    HERMES_USER_MD.parent.mkdir(parents=True, exist_ok=True)
    new_content = build_user_md()

    if HERMES_USER_MD.exists():
        old_content = HERMES_USER_MD.read_text(encoding="utf-8")
        if old_content.strip() == new_content.strip():
            print(f"No change: {HERMES_USER_MD}")
            return 0
        diff = difflib.unified_diff(
            old_content.splitlines(keepends=True),
            new_content.splitlines(keepends=True),
            fromfile="USER.md (current)",
            tofile="USER.md (new)",
        )
        print("".join(diff))
    else:
        print(f"Creating {HERMES_USER_MD} (no existing file to diff against)")

    if "--write" not in sys.argv:
        print("\nRe-run with --write to apply.", file=sys.stderr)
        return 1

    HERMES_USER_MD.write_text(new_content, encoding="utf-8")
    print(f"\nWrote {HERMES_USER_MD}")
    return 0


if __name__ == "__main__":
    sys.exit(main())